cargo-features = ["profile-rustflags"]

[package]
name = "barbell"
version = "0.1.6"
edition = "2024"

repository = "https://github.com/rickbeeloo/barbell-sg"

[lib]
name = "barbell"
path = "src/lib.rs"

[[bin]]
name = "barbell"
path = "src/main.rs"

[dependencies]
pa-bitpacking = { git = "https://github.com/RagnarGrootKoerkamp/astar-pairwise-aligner.git", branch = "master" }
pa-types = { git = "https://github.com/pairwise-alignment/pa-types" }
rand = "0.8"
spinners = "4.1.1"
indicatif = "0.17.11"
colored = "2.0.0"
rayon = "1.10.0"
seq_io_parallel = {git = "https://github.com/rickbeeloo/seq_io_parallel_index.git", branch = "main"}
seq_io = "0.3.1"
clap = { version = "4.4", features = ["derive"] }
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0.98"
tempfile = "3.2"

[dev-dependencies]
serde_json = "1.0"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"